name: Publish dry run

on: [push, pull_request]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          accesscredentialJsonToken: ${{ secrets.CREDENTIALS }}
