name: Publish dry run

on: [push, pull_request]

jobs:

  publish-dry-run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish dry run
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIALS }}
          dryRunOnly: true
